
```{r, child = "../setup.Rmd", include = FALSE}
```

This page describes the native storage types supported by vctrs at C level. Every vctrs algorithm, like the one underlying `vec_match()`, is guaranteed to work with the native storage types.

Supported native storage types:

- Logical (`LGLSXP`)
- Integer (`INTSXP`)
- Double (`REALSXP`)
- Complex (`CPLSXP`)
- Raw (`RAWSXP`)
- Character (`STRSXP`)
- List (`VECSXP`)
- Arrays, denoted by the presence of a `dim` attribute and one of the above storage types.
- Data frames, denoted by the presence of `names` and `row.names` attributes, a `class` attribute of `"data.frame"`, and a storage type of list (`VECSXP`). Data frame columns may contain any storage type mentioned here, including arrays and additional data frames.

In addition to the required attributes mentioned above, the only other attribute that is natively supported by vctrs on these storage types is their names:

- For atomics, the `names` attribute
- For arrays, the `dimnames` attribute, but only row names are natively supported
- For data frames, the `row.names` attribute

## `vec_unstructure()`

`vec_unstructure()` takes an object that meets the native storage requirements and strips away all extraneous attributes, leaving behind only the attributes that are natively supported, as described above. This is often useful for avoiding unexpected S3 dispatch on classed objects from within vctrs algorithms.

## `vec_proxy()`

`vec_proxy()` takes an arbitrary vector supported by vctrs (as defined by `obj_is_vector()`) and returns an object that meets vctrs's native storage requirements. It is the job of the class author to define the mapping from custom vector class to a vctrs native storage type. If the custom vector builds on top of a native storage type, then a `vec_proxy()` method can return its input unmodified. The result of a `vec_proxy()` method is then further processed by `vec_unstructure()` to strip away extraneous attributes. This is then manipulated by the C level algorithms of vctrs, which support all native storage types.
