// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/vctrs.h"
#include <Rcpp.h>

using namespace Rcpp;

// combine
SEXP combine(SEXP x1, SEXP x2);
RcppExport SEXP vctrs_combine(SEXP x1SEXP, SEXP x2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type x2(x2SEXP);
    rcpp_result_gen = Rcpp::wrap(combine(x1, x2));
    return rcpp_result_gen;
END_RCPP
}
